### ISSUE TITLE
Missing /2 in amplitude spectrum?

### ISSUE THREAD

**Issue by arjunsavel** [SterlingYM/astroPIPS#32]
In tossing a simple sine wave through the amplitude spectrum function, it seems as though it returns twice the amplitude at the given period. Potential bug, or have I missed something?

![Screen Shot 2021-02-28 at 7 57 53 PM](https://user-images.githubusercontent.com/35353555/109440189-28454780-79e6-11eb-9f76-5ab7556029d5.jpg)

**Comment by SterlingYM** [comment]
This is due to the convention in pulsating variable star studies to call peak-to-peak magnitude difference the amplitude. What is the convention in the exoplanet community?

**Comment by arjunsavel** [comment]
Pretty sure we use half peak-to-peak magnitude! It'd be fine to keep this magnitude implementation in, though, so long as it's documented as such.
