### ISSUE TITLE
Make multiprocessing optional?

### ISSUE THREAD

**Issue by arjunsavel** [SterlingYM/astroPIPS#4]
Not all users might want to use multiprocessing — especially if they're running scripts that spawn processes, themselves.

**Comment by SterlingYM** [comment]
We should look into more efficient and careful implementation methods for multiprocessing (e.g. #14). I'll take care of this

**Comment by SterlingYM** [comment]
Multiprocessing seems to be very unstable on different platforms. We should definitely make it easier to turn multiprocessing off entirely, probably by adding a new PIPS configuration class or something

**Comment by SterlingYM** [comment]
So far ```multiprocessing=False``` argument turns off multiprocessing in ```periodogram()``` and ```get_period()``` functions. Should we add global parameter? Another easy implementation is to add attributes to ```photdata``` class.
